### ISSUE TITLE
No such file or directory: 'bin/mapping.p'

### ISSUE THREAD

**Issue by tschmidt64** [Coopss/EMNIST#1]
When running training.py, it looks for a file in 'bin/', which as far as I can tell, doesn't exist. My assumption is that on your local repo there was a ./bin/ directory but git ignored it when pushing?

**Comment by ryanjcooper** [comment]
Sorry for the response delay; yes, I did not push bin/ to git as it contains binary and model files. I will add a method to automatically create this in the future. As a workaround, create the directory and you should have no problems.

**Comment by ryanjcooper** [comment]
@tschmidt64 see 74d75aee69a3a515b2df64f0bc67c9a6f4124b25
