### ISSUE TITLE
IndexError: index 26 is out of bounds for axis 1 with size 26

### ISSUE THREAD

**Issue by vganeshbabuagiliz** [Coopss/EMNIST#10]
Dear Ryan Cooper, I faced an issue when I try to train the letters only dataset emnist-letters.mat when I run the training - I get the below error - can you help?

![image](https://user-images.githubusercontent.com/13791034/42514415-0223af5e-8477-11e8-8100-ae4348ced0c5.png)

**Comment by ryanjcooper** [comment]
Hi there, I've seen this error before with TensorFlow and Keras version mismatching. If you could compare your version of these dependencies to the ones listed in dependencies.txt and ensure that they are matching. The version of Keras that this model was developed under may not be forward compatible.

Let me know if this works for you,
Ryan

**Comment by ryanjcooper** [comment]
Closing as no response.
