### ISSUE TITLE
Can you help me with the usage?

### ISSUE THREAD

**Issue by wonwooddo** [Coopss/EMNIST#2]
Hi. firstly, thankyou for the wonderful work to test MNIST clissifier model that trained by keras.

but I dont get to how to run "trining.py" to get model.
I cloned your git rep and  download "data/mnist_all.mat" from "http://www.cs.nyu.edu/~roweis/data.html"
and give to --file option like above.

`python3 training.py --file ./mnist_all.mat`

but the log sais
```
  File "training.py", line 57, in load_data
    mapping = {kv[0]:kv[1:][0] for kv in mat['dataset'][0][0][2]}
KeyError: 'dataset'

```

looks like the  .mat file data is wrong.

can you tell me what .mat file I have to use and explain more about usage?

thank you

**Comment by ryanjcooper** [comment]
Hello, thanks for your interest in the project!
I am sorry if the database download was not clear, I will add a more direct link to the documentation.
Here is the [direct link](https://cloudstor.aarnet.edu.au/plus/index.php/s/7YXcasTXp727EqB/download) to download all of the matlab files; in this project, only the emnist-byclass.mat is used.

Let me know if you have any more issues.
